"""
Impact API endpoints — api/v1/impact.py

GET /impact/public       — cached 30 s, no auth required
GET /donor/impact        — donor only
GET /org/impact          — recipient only
"""

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import Role
from app.core.deps import require_role
from app.db.session import get_db
from app.schemas.impact import ImpactSummary
from app.services.impact import get_donor_impact, get_org_impact, get_public_impact

router = APIRouter(tags=["impact"])

# Simple in-process cache for public impact (30 s TTL)
_public_cache: ImpactSummary | None = None
_public_cache_ts: float = 0.0
_PUBLIC_CACHE_TTL_S = 30.0


@router.get("/impact/public", response_model=ImpactSummary, summary="Public landing impact counters")
async def public_impact(db: AsyncSession = Depends(get_db)) -> ImpactSummary:
    """
    Aggregate impact counters for the public landing page.
    Cached for 30 seconds.
    """
    import time

    global _public_cache, _public_cache_ts
    now = time.monotonic()
    if _public_cache is not None and (now - _public_cache_ts) < _PUBLIC_CACHE_TTL_S:
        return _public_cache

    result = await get_public_impact(db)
    _public_cache = result
    _public_cache_ts = now
    return result


@router.get("/donor/impact", response_model=ImpactSummary, summary="Donor personal impact")
async def donor_impact(
    current_user=Depends(require_role(Role.DONOR)),
    db: AsyncSession = Depends(get_db),
) -> ImpactSummary:
    """Return the impact generated by this donor's donations."""
    return await get_donor_impact(db, donor_id=current_user.id)


@router.get("/org/impact", response_model=ImpactSummary, summary="Recipient org impact")
async def org_impact(
    current_user=Depends(require_role(Role.RECIPIENT)),
    db: AsyncSession = Depends(get_db),
) -> ImpactSummary:
    """Return the impact received by this recipient org."""
    return await get_org_impact(db, org_id=current_user.id)
