"""initial_schema

Revision ID: 36165391e7e0
Revises:
Create Date: 2026-09-24 17:26:36.455859

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36165391e7e0"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("entity", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("before", sa.JSON(), nullable=True),
        sa.Column("after", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_events_at"), "audit_events", ["at"], unique=False)
    op.create_index(op.f("ix_audit_events_entity"), "audit_events", ["entity"], unique=False)
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        "ix_audit_events_entity_lookup", "audit_events", ["entity", "entity_id"], unique=False
    )
    op.create_table(
        "food_safety_rules",
        sa.Column(
            "storage",
            sa.Enum(
                "AMBIENT", "HOT", "COLD", name="storagecondition", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("max_hours", sa.Float(), nullable=False),
        sa.Column("transit_cap_minutes", sa.Integer(), nullable=False),
        sa.Column("handling_buffer_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=100), nullable=False),
        sa.Column("endpoint", sa.String(length=255), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_idempotency_key_user_endpoint",
        "idempotency_keys",
        ["key", "user_id", "endpoint"],
        unique=True,
    )
    op.create_index(op.f("ix_idempotency_keys_key"), "idempotency_keys", ["key"], unique=False)
    op.create_index(
        op.f("ix_idempotency_keys_user_id"), "idempotency_keys", ["user_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column(
            "role",
            sa.Enum(
                "DONOR", "RECIPIENT", "DRIVER", "ADMIN", name="role", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "donors",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("org_name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("fssai_no", sa.String(length=50), nullable=True),
        sa.Column("default_pickup_window", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_donors_lat"), "donors", ["lat"], unique=False)
    op.create_index(op.f("ix_donors_lng"), "donors", ["lng"], unique=False)
    op.create_index(op.f("ix_donors_user_id"), "donors", ["user_id"], unique=True)
    op.create_table(
        "drivers",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "vehicle_type",
            sa.Enum(
                "BICYCLE",
                "SCOOTER",
                "E_RICKSHAW",
                "VAN",
                name="vehicletype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("capacity_portions", sa.Integer(), nullable=False),
        sa.Column("has_cold_box", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OFFLINE",
                "AVAILABLE",
                "ON_TASK",
                "STALE",
                name="driverstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("last_ping_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accept_rate_ewma", sa.Float(), nullable=False),
        sa.Column("speed_factor_ewma", sa.Float(), nullable=False),
        sa.Column("service_radius_m", sa.Float(), nullable=False),
        sa.Column("shift_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_status"), "drivers", ["status"], unique=False)
    op.create_index(op.f("ix_drivers_user_id"), "drivers", ["user_id"], unique=True)
    op.create_table(
        "recipient_orgs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("fssai_reg_no", sa.String(length=50), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepts_diets", sa.JSON(), nullable=False),
        sa.Column("accepts_storage", sa.JSON(), nullable=False),
        sa.Column("cold_max_units", sa.Integer(), nullable=False),
        sa.Column("service_rate_per_hour", sa.Float(), nullable=False),
        sa.Column("need_level", sa.Float(), nullable=False),
        sa.Column("is_open_override", sa.Boolean(), nullable=True),
        sa.Column("last_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reliability_ewma", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipient_orgs_lat"), "recipient_orgs", ["lat"], unique=False)
    op.create_index(op.f("ix_recipient_orgs_lng"), "recipient_orgs", ["lng"], unique=False)
    op.create_index(op.f("ix_recipient_orgs_user_id"), "recipient_orgs", ["user_id"], unique=True)
    op.create_table(
        "capacity_adjustments",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("delta_portions", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["recipient_orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capacity_adjustments_org_id"), "capacity_adjustments", ["org_id"], unique=False
    )
    op.create_table(
        "capacity_windows",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("dow", sa.Integer(), nullable=True),
        sa.Column("specific_date", sa.Date(), nullable=True),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("max_portions", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["org_id"], ["recipient_orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capacity_windows_org_id"), "capacity_windows", ["org_id"], unique=False
    )
    op.create_table(
        "donations",
        sa.Column("donor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "POSTED",
                "MATCHING",
                "PARTIALLY_MATCHED",
                "MATCHED",
                "IN_TRANSIT",
                "DELIVERED",
                "EXPIRED",
                "FALLBACK",
                "CANCELLED",
                name="donationstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "diet",
            sa.Enum("VEG", "EGG", "NON_VEG", name="diettype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "storage",
            sa.Enum(
                "AMBIENT", "HOT", "COLD", name="storagecondition", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("total_portions", sa.Integer(), nullable=False),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("best_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("safe_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pickup_lat", sa.Float(), nullable=False),
        sa.Column("pickup_lng", sa.Float(), nullable=False),
        sa.Column("pickup_address", sa.String(length=500), nullable=False),
        sa.Column("photo_url", sa.String(length=1000), nullable=True),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("parse_confidence", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["donor_id"], ["donors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_donations_active_status", "donations", ["status"], unique=False)
    op.create_index(op.f("ix_donations_donor_id"), "donations", ["donor_id"], unique=False)
    op.create_index(op.f("ix_donations_status"), "donations", ["status"], unique=False)
    op.create_table(
        "driver_locations",
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("heading", sa.Float(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_driver_locations_at"), "driver_locations", ["at"], unique=False)
    op.create_index(
        op.f("ix_driver_locations_driver_id"), "driver_locations", ["driver_id"], unique=False
    )
    op.create_table(
        "routes",
        sa.Column("driver_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("planned_distance_m", sa.Float(), nullable=False),
        sa.Column("planned_duration_s", sa.Float(), nullable=False),
        sa.Column("polyline", sa.JSON(), nullable=True),
        sa.Column("replanned_reason", sa.String(length=50), nullable=True),
        sa.Column("saved_seconds_vs_previous", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_routes_driver_id"), "routes", ["driver_id"], unique=False)
    op.create_table(
        "allocations",
        sa.Column("donation_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("portions", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OFFERED",
                "ACCEPTED",
                "DRIVER_PENDING",
                "DRIVER_ASSIGNED",
                "PICKED_UP",
                "DELIVERED",
                "DECLINED",
                "EXPIRED",
                "CANCELLED",
                "FAILED",
                name="allocationstatus",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("container_label", sa.String(length=50), nullable=False),
        sa.Column("predicted_delivery", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slack_seconds", sa.Float(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("pickup_otp_hash", sa.String(length=255), nullable=True),
        sa.Column("dropoff_otp_hash", sa.String(length=255), nullable=True),
        sa.Column("driver_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["donation_id"], ["donations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["driver_id"], ["drivers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipient_id"], ["recipient_orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_allocations_donation_id"), "allocations", ["donation_id"], unique=False
    )
    op.create_index(op.f("ix_allocations_driver_id"), "allocations", ["driver_id"], unique=False)
    op.create_index(
        op.f("ix_allocations_recipient_id"), "allocations", ["recipient_id"], unique=False
    )
    op.create_index(op.f("ix_allocations_status"), "allocations", ["status"], unique=False)
    op.create_table(
        "donation_items",
        sa.Column("donation_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("portions", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["donation_id"], ["donations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_donation_items_donation_id"), "donation_items", ["donation_id"], unique=False
    )
    op.create_table(
        "capacity_reservations",
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_id", sa.Uuid(), nullable=True),
        sa.Column("portions", sa.Integer(), nullable=False),
        sa.Column("cold_units", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("held_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("arrives_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["recipient_orgs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capacity_reservations_allocation_id"),
        "capacity_reservations",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capacity_reservations_held_until"),
        "capacity_reservations",
        ["held_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_capacity_reservations_org_id"), "capacity_reservations", ["org_id"], unique=False
    )
    op.create_index(
        "ix_capacity_reservations_org_state",
        "capacity_reservations",
        ["org_id", "state"],
        unique=False,
    )
    op.create_table(
        "impact_ledger",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("meals", sa.Integer(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=False),
        sa.Column("co2e_kg", sa.Float(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_impact_ledger_allocation_id"), "impact_ledger", ["allocation_id"], unique=True
    )
    op.create_table(
        "offers",
        sa.Column(
            "kind",
            sa.Enum("RECIPIENT", "DRIVER", name="offerkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("allocation_id", sa.Uuid(), nullable=True),
        sa.Column("route_preview", sa.JSON(), nullable=True),
        sa.Column("target_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "DECLINED",
                "EXPIRED",
                "WITHDRAWN",
                name="offerstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_offers_allocation_id"), "offers", ["allocation_id"], unique=False)
    op.create_index(op.f("ix_offers_expires_at"), "offers", ["expires_at"], unique=False)
    op.create_index("ix_offers_pending_expiry", "offers", ["expires_at", "status"], unique=False)
    op.create_index(op.f("ix_offers_status"), "offers", ["status"], unique=False)
    op.create_index(op.f("ix_offers_target_user_id"), "offers", ["target_user_id"], unique=False)
    op.create_table(
        "route_stops",
        sa.Column("route_id", sa.Uuid(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PICKUP", "DROPOFF", name="stoptype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("planned_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_arrival", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slack_seconds", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ARRIVED",
                "DONE",
                "SKIPPED",
                "FAILED",
                name="stopstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("arrived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("proof_photo_url", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["allocation_id"], ["allocations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["route_id"], ["routes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_stops_allocation_id"), "route_stops", ["allocation_id"], unique=False
    )
    op.create_index(op.f("ix_route_stops_route_id"), "route_stops", ["route_id"], unique=False)
    op.create_index("ix_route_stops_route_seq", "route_stops", ["route_id", "seq"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_route_stops_route_seq", table_name="route_stops")
    op.drop_index(op.f("ix_route_stops_route_id"), table_name="route_stops")
    op.drop_index(op.f("ix_route_stops_allocation_id"), table_name="route_stops")
    op.drop_table("route_stops")
    op.drop_index(op.f("ix_offers_target_user_id"), table_name="offers")
    op.drop_index(op.f("ix_offers_status"), table_name="offers")
    op.drop_index("ix_offers_pending_expiry", table_name="offers")
    op.drop_index(op.f("ix_offers_expires_at"), table_name="offers")
    op.drop_index(op.f("ix_offers_allocation_id"), table_name="offers")
    op.drop_table("offers")
    op.drop_index(op.f("ix_impact_ledger_allocation_id"), table_name="impact_ledger")
    op.drop_table("impact_ledger")
    op.drop_index("ix_capacity_reservations_org_state", table_name="capacity_reservations")
    op.drop_index(op.f("ix_capacity_reservations_org_id"), table_name="capacity_reservations")
    op.drop_index(op.f("ix_capacity_reservations_held_until"), table_name="capacity_reservations")
    op.drop_index(
        op.f("ix_capacity_reservations_allocation_id"), table_name="capacity_reservations"
    )
    op.drop_table("capacity_reservations")
    op.drop_index(op.f("ix_donation_items_donation_id"), table_name="donation_items")
    op.drop_table("donation_items")
    op.drop_index(op.f("ix_allocations_status"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_recipient_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_driver_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_donation_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_routes_driver_id"), table_name="routes")
    op.drop_table("routes")
    op.drop_index(op.f("ix_driver_locations_driver_id"), table_name="driver_locations")
    op.drop_index(op.f("ix_driver_locations_at"), table_name="driver_locations")
    op.drop_table("driver_locations")
    op.drop_index(op.f("ix_donations_status"), table_name="donations")
    op.drop_index(op.f("ix_donations_donor_id"), table_name="donations")
    op.drop_index("ix_donations_active_status", table_name="donations")
    op.drop_table("donations")
    op.drop_index(op.f("ix_capacity_windows_org_id"), table_name="capacity_windows")
    op.drop_table("capacity_windows")
    op.drop_index(op.f("ix_capacity_adjustments_org_id"), table_name="capacity_adjustments")
    op.drop_table("capacity_adjustments")
    op.drop_index(op.f("ix_recipient_orgs_user_id"), table_name="recipient_orgs")
    op.drop_index(op.f("ix_recipient_orgs_lng"), table_name="recipient_orgs")
    op.drop_index(op.f("ix_recipient_orgs_lat"), table_name="recipient_orgs")
    op.drop_table("recipient_orgs")
    op.drop_index(op.f("ix_drivers_user_id"), table_name="drivers")
    op.drop_index(op.f("ix_drivers_status"), table_name="drivers")
    op.drop_table("drivers")
    op.drop_index(op.f("ix_donors_user_id"), table_name="donors")
    op.drop_index(op.f("ix_donors_lng"), table_name="donors")
    op.drop_index(op.f("ix_donors_lat"), table_name="donors")
    op.drop_table("donors")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_idempotency_keys_user_id"), table_name="idempotency_keys")
    op.drop_index(op.f("ix_idempotency_keys_key"), table_name="idempotency_keys")
    op.drop_index("ix_idempotency_key_user_endpoint", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_table("food_safety_rules")
    op.drop_index("ix_audit_events_entity_lookup", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
